-- SELECT * FROM albums;
-- SELECT * FROM albums WHERE relese_date <1980;
-- SELECT * FROM albums WHERE artist = "Michael Jackson";
-- UPDATE albums SET sales = sales*10;
-- UPDATE albums SET release_date = release_date - 100 WHERE release_date <1980;
-- UPDATE albums Set artist = 'Peter Jackson' WHERE artist = "Michael Jackson";
